nameOverride: ""
fullnameOverride: ""

image:
  repository: elementsproject/lightningd
  tag: v23.05.1
  pullPolicy: IfNotPresent

clientImage:
  repository: scalingln/cln-client
  tag: latest
  pullPolicy: Always

bitcoind:
  rpcPort: 18443
  rpcUser: foo
  rpcPass: pass
  rpcHost: bitcoind

port: 9735
gRPCPort: 8383

clientPort: 8181

network: regtest

# set to one of the endpoints defined in traefik's values file e.g. (endpoint1, endpoint2, endpoint3, endpoint4)
# to expose direct gRPC access to the node
gRPCEntryPoint: null

# This gives persistence to nodes. If no storage is set then the node will be ephemeral between upgrades.
volume:
  size: "" # example 1Gi for 1 gibibyte (1024^3 bytes). Blank string for no storage.
  storageClass: "" # example do-block-storage for DigitalOcean's standard block storage. Blank for default storage class.
